### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by Hadil66** [RubenErhardt/the-startup-responsive-interactieve-website#1]
Slim dat je de font zo gebruikt. 

https://github.com/RubenErhardt/the-startup-responsive-interactieve-website/blob/c5e4ba75ca58136fa27cd5105264e0bee4f42432/styles/style.css#L15

https://github.com/RubenErhardt/the-startup-responsive-interactieve-website/blob/c5e4ba75ca58136fa27cd5105264e0bee4f42432/index.html#L10

**Comment by RubenErhardt** [comment]
Dankjewel

**Comment by Hadil66** [comment]
Geen dank! Ik heb het nu zelf ook zo gedaan.
