### ISSUE TITLE
Overweeg om <article> te gebruiken voor de sectie met de teamtekst

### ISSUE THREAD

**Issue by Daan645** [RubenErhardt/the-startup-responsive-interactieve-website#10]
Overweeg om <article> te gebruiken voor de sectie met de teamtekst, omdat het om inhoudelijke secties gaat.

Bijvoorbeeld op deze manier:
```<article>
  <div class="container">
    <section class="teams">
      <!-- ... huidige inhoud van de teamsectie ... -->
    </section>
  </div>
</article>
```

https://github.com/RubenErhardt/the-startup-responsive-interactieve-website/blob/576e72789691b0b1c35bd593f0b57a828d8f6b2a/index.html#L56-L66

**Comment by RubenErhardt** [comment]
<article>
        <div class="container">
          <section class="teams">
            <div class="text-container">
              <h1>Meet our <span class="team-text">team</span></h1>
              <p>
                "We empower companies to transform their aspirations into reality. As a carefully curated collective of global experts, we share a common objective: crafting brands and digital experiences that redefine industries, leave a lasting impact, influence culture, and foster meaningful connections. Together, we bring dreams to life and inspire positive change."
              </p>
            </div>
            <div class="groepsfoto">
              <img src="images/team-images/gruppenfoto.png" alt="groepsfoto" height="auto">
            </div>
          </section>   
        </div>
      </article> 

Gedaan
