### ISSUE TITLE
Dubbele initialisering variabelen javascript

### ISSUE THREAD

**Issue by MokhtarAkle** [RubenErhardt/the-startup-responsive-interactieve-website#12]
https://github.com/RubenErhardt/the-startup-responsive-interactieve-website/blob/576e72789691b0b1c35bd593f0b57a828d8f6b2a/scripts/script.js#L2

https://github.com/RubenErhardt/the-startup-responsive-interactieve-website/blob/576e72789691b0b1c35bd593f0b57a828d8f6b2a/scripts/script.js#L17

Je gebruikt in je Javascript een variabele meerdere keren maar definieert deze ook meerdere keren. Dit was waarschijnlijk nodig omdat je deze variabele hebt gedefinieerd in een functie. Door de variabele buiten de functie en bijv. de top van de pagina te definieren, kan je deze in het gehele Javascript bestand gebruiken.

Bron: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables#what_is_a_variable

**Comment by MokhtarAkle** [comment]
Hetzelfde geldt trouwens voor de volgende functie:
https://github.com/RubenErhardt/the-startup-responsive-interactieve-website/blob/576e72789691b0b1c35bd593f0b57a828d8f6b2a/scripts/script.js#L10-L14

Door deze functie buiten de huidige functie te initialiseren kan je deze in de rest van de pagina gebruiken door de functie naam te roepen.

Bron: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions#calling_functions

**Comment by RubenErhardt** [comment]
function toggleMenu(show) {
  const menuOverlay = document.getElementById('menuOverlay');
  const menuContent = document.querySelector('.menu-content');
  const images = document.querySelectorAll('img');

  menuOverlay.classList.toggle('show', show);
  menuContent.classList.toggle('show', show);

  // Verberg alle afbeeldingen met vertraging
  images.forEach((img, index) => {
    img.style.transition = `opacity 0.5s ${index * 0.1}s`; // Aangepaste vertraging per afbeelding
    img.style.opacity = show ? '0' : '1';
  });
}

document.getElementById('openMenu').addEventListener('click', function() {
  toggleMenu(true);
});

document.getElementById('closeMenu').addEventListener('click', function() {
  toggleMenu(false);
}); door de vorige issue heb ik deze eigenlijk nu ook opgelost :)
