### ISSUE TITLE
classList.toggle ipv classList.add & classList.remove

### ISSUE THREAD

**Issue by MokhtarAkle** [RubenErhardt/the-startup-responsive-interactieve-website#13]
https://github.com/RubenErhardt/the-startup-responsive-interactieve-website/blob/576e72789691b0b1c35bd593f0b57a828d8f6b2a/scripts/script.js#L6

https://github.com/RubenErhardt/the-startup-responsive-interactieve-website/blob/576e72789691b0b1c35bd593f0b57a828d8f6b2a/scripts/script.js#L21

Een kleine suggestie maar tevens een tijdebesparende suggestie, classList.toggle combineert beide functies in 1 functie die je vervolgens kan gebruiken met je eventlisteners.

Bron: https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

**Comment by RubenErhardt** [comment]
function toggleMenu(show) {
  const menuOverlay = document.getElementById('menuOverlay');
  const menuContent = document.querySelector('.menu-content');
  const images = document.querySelectorAll('img');

  menuOverlay.classList.toggle('show', show);
  menuContent.classList.toggle('show', show);

  // Verberg alle afbeeldingen met vertraging
  images.forEach((img, index) => {
    img.style.transition = `opacity 0.5s ${index * 0.1}s`; // Aangepaste vertraging per afbeelding
    img.style.opacity = show ? '0' : '1';
  });
}

document.getElementById('openMenu').addEventListener('click', function() {
  toggleMenu(true);
});

document.getElementById('closeMenu').addEventListener('click', function() {
  toggleMenu(false);
});

ik heb hem zo opgelost!
