### ISSUE TITLE
Er mist iets in de link

### ISSUE THREAD

**Issue by saschavanvliett** [RubenErhardt/the-startup-responsive-interactieve-website#14]
Je moet bij de <link een href toevoegen.
<img width="633" alt="image" src="https://github.com/RubenErhardt/the-startup-responsive-interactieve-website/assets/144007519/1eb946cf-5f58-4984-8cf4-ff0a74b8a075">

**Comment by RubenErhardt** [comment]
Ook dit weer is niet van mij haha.
