### ISSUE TITLE
Icon attribuut

### ISSUE THREAD

**Issue by saschavanvliett** [RubenErhardt/the-startup-responsive-interactieve-website#15]
Je mag geen icon attribuut toevoegen op het a element
<img width="665" alt="image" src="https://github.com/RubenErhardt/the-startup-responsive-interactieve-website/assets/144007519/f36abb12-e3e5-493b-8efe-5b28a5277e9b">

**Comment by RubenErhardt** [comment]
Dit is niet eens van mij maar van github zelf volgensmij?
