### ISSUE TITLE
Kruisje groter

### ISSUE THREAD

**Issue by saschavanvliett** [RubenErhardt/the-startup-responsive-interactieve-website#16]
Misschien kan je een groter kruisje maken bij het sluiten van het menu! En een optie maken waarbij je alle personen bij elkaar kunt zien.

**Comment by RubenErhardt** [comment]
.close-btn {
  position: absolute;
  top: 20px;
  right: 10px;
  **font-size: 40px;**
  cursor: pointer;
}

.close-btn:hover {
  color: red;
}

.close-btn::before {
  content: attr(data-tooltip);
  **font-size: 20px;**
  position: absolute;
  left: -100px;
  transform: translateX(-50%);
  padding: 3px; 
  background-color: rgba(0, 0, 0, 0.7);
  color: #fff;
  border-radius: 3px; 
  white-space: nowrap;
  opacity: 0;
  transition: opacity 0.3s ease-in-out;
}
**_Kruisje groter gemaakt, datatooltip grote hetzelfde gehouden_**

  <div class="containerTeam">
    <select id="teamSelector">
      <option value="TDT">The Development Team</option>
      <option value="MARKETING">Marketing Team</option>
      <option value="UI-TEAM">Ui Team</option>
      <option value="alle-teams">Alle Teams</option>
    </select>
  </div>

document.getElementById('teamSelector').addEventListener('change', function () {
  var selectedTeam = this.value;
  var teamSections = document.querySelectorAll('.team-section');

  teamSections.forEach(function (section) {
    section.style.display = 'none';
  });

  if (selectedTeam === 'alle-teams') {
    teamSections.forEach(function (section) {
      section.style.display = 'flex';
    });
  } else {
    document.getElementById(selectedTeam).style.display = 'flex';
  }
});

**_Ook heb ik een optie alle teams laten zien toegevoegd_**
