### ISSUE TITLE
Class & ID in 1 element is geen probleem maar vaak onnodig.

### ISSUE THREAD

**Issue by MokhtarAkle** [RubenErhardt/the-startup-responsive-interactieve-website#6]
https://github.com/RubenErhardt/the-startup-responsive-interactieve-website/blob/576e72789691b0b1c35bd593f0b57a828d8f6b2a/index.html#L42

Je gebruikt op het moment in meerdere plaatsen een id en class tegelijk om een element vervolgens te gebruiken in Javascript. Alhoewel er helemaal geen probleem is met beide gebruiken, is het vaak onnodig. Over het algemeen wil je een id gebruiken om een uniek element te noteren en een class voor elementen die vaker voorkomen. 

Als refresher: https://www.bestcolleges.com/bootcamps/guides/css-class-vs-id/ 
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class

**Comment by RubenErhardt** [comment]
Dankjewel voor de tip
