### ISSUE TITLE
Onduidelijke/verwarrende class names

### ISSUE THREAD

**Issue by MokhtarAkle** [RubenErhardt/the-startup-responsive-interactieve-website#8]
https://github.com/RubenErhardt/the-startup-responsive-interactieve-website/blob/576e72789691b0b1c35bd593f0b57a828d8f6b2a/index.html#L70

Het is verwarrend als je classes zoals "buttons" gaat gebruiken als een element "button" heet. Verder geeft een classname zoals button1 niet goed aan wat voor een element er geselecteerd wordt. Dit is geen probleem als je alleen werkt maar zodra je met andere gaat werken kan dit een probleem worden. Probeer daarom descriptieve class names te gebruiken om jezelf en je teammates te helpen.

Bron: https://www.w3.org/QA/Tips/goodclassnames#:~:text=warning%20%2C%20important%20%2C%20downloadableImage%20and%20submenu,look%20of%20the%20page%20changes.&text=border4px%20%2C%20lighttext%20and%20prettybackground%20are%20examples%20of%20bad%20names.

**Comment by RubenErhardt** [comment]
``` <button class="button-services">Services &#8594;</button>
      <button class="button-contact">Contact &#8594;</button>

Je hebt gelijk ik heb t aangepast
