### ISSUE TITLE
Label toevoegen aan select

### ISSUE THREAD

**Issue by Daan645** [RubenErhardt/the-startup-responsive-interactieve-website#9]
Je zou voor je select een label kunnen toevoegen zodat het duidelijker is voor de gebruiker wat ze selecteren.

Bijvoorbeeld zo:
`
<label for="teamSelector">Select a Team:</label>
<select id="teamSelector">
`

https://github.com/RubenErhardt/the-startup-responsive-interactieve-website/blob/576e72789691b0b1c35bd593f0b57a828d8f6b2a/index.html#L75C7-L75C31

**Comment by RubenErhardt** [comment]
``` <div class="containerTeam">
      <label for="teamSelector">Select a Team:</label>
      <select id="teamSelector">
        <option value="TDT">The Development Team</option>
        <option value="MARKETING">Marketing Team</option>
        <option value="UI-TEAM">UI Team</option>
        <option value="alle-teams">Alle Teams</option>
      </select>
    </div>```
     Tnx goede tip Daan
